[package]
name = "engine"
version = "0.1.0"
authors = ["Anders Rein <andersrein87@gmail.com>"]

[target.'cfg(windows)'.dependencies]
sdl2 = { version = "0.32.1", features = ["bundled"] }
[target.'cfg(unix)'.dependencies]
sdl2 = { version = "0.31.0" }

[dependencies]
stb_image = "0.2.1"
rand = "0.6.4"
serde_json = "1.0"
serde = "1.0.85"
serde_derive = "1.0.85"
